(function(){
    module.config({
        'base':'js/',
        'require':true,
        //'nocache':true,
        'mined':'min',
        'dirs':{},
        'alias':{
            'jquery':'//code.jquery.com/jquery-2.0.3',
            'jquery.module':'{modules}/jquery.module',
            
            'os':'{plugins}/os',
            'touchevent':'{plugins}/touchevent'
        },
        'files':[],
        'globals':{
            '$':'jquery.module'
        }
    });
})();